In [6]:
from sqlalchemy import create_engine

engine = create_engine('postgresql://postgres:Korsarz7@localhost:5432/postgres')

In [7]:
import pandas as pd

df = pd.read_csv('players_data-2025_2026.csv')
df.columns = df.columns.str.lower()

In [8]:
df_clean = df.dropna(subset=['age'])

In [9]:
df_clean.to_sql('players_python', engine, if_exists='replace', index=False)

277

In [10]:
wynik = pd.read_sql_query("SELECT comp, COUNT(*) FROM players_python GROUP BY comp", engine)
wynik

                 comp  count
0          es La Liga    610
1       de Bundesliga    507
2  eng Premier League    551
3          it Serie A    608
4          fr Ligue 1    561

In [11]:
zapytanie = """
WITH avg_by_league AS (
    SELECT comp, AVG(age) AS avg_age
    FROM players_python
    GROUP BY comp
)
SELECT * FROM avg_by_league ORDER BY avg_age DESC
"""

wynik2 = pd.read_sql_query(zapytanie, engine)
wynik2

                 comp    avg_age
0          es La Liga  25.434426
1          it Serie A  25.266447
2  eng Premier League  24.851180
3       de Bundesliga  24.676529
4          fr Ligue 1  23.948307