In [70]:
import pandas as pd

df = pd.read_csv('players_data-2025_2026.csv')
df.columns = df.columns.str.lower()

df.shape

(2839, 102)

In [71]:
df.head()

,rk,player,nation,pos,squad,comp,age,born,mp,starts,...,crdy_stats_misc,crdr_stats_misc,2crdy,fls,fld,off,crs,int,tklw,og
0,1,Brenden Aaronson,us USA,"MF,FW",Leeds United,eng Premier League,24.0,2000.0,37,30,...,3,0,0,20,51,5,37,17,27,0
1,2,Jerome Abbey,eng ENG,MF,Wolves,eng Premier League,15.0,2009.0,1,0,...,0,0,0,0,0,1,0,1,0,0
2,3,Zach Abbott,eng ENG,DF,Nottingham Forest,eng Premier League,19.0,2006.0,3,2,...,0,0,0,3,1,0,3,2,4,0
3,4,Jones El-Abdellaoui,ma MAR,"MF,FW",Celta Vigo,es La Liga,19.0,2006.0,22,4,...,0,0,0,7,3,2,30,3,3,0
4,5,Himad Abdelli,dz ALG,MF,Marseille,fr Ligue 1,25.0,1999.0,8,1,...,1,0,0,3,0,0,1,2,1,0

In [72]:
df.dtypes.age

dtype('float64')

In [73]:

df.dtypes.gls

dtype('int64')

In [74]:
df['age'].isnull().sum()

np.int64(2)

In [75]:
df[df['age'].isnull()]

,rk,player,nation,pos,squad,comp,age,born,mp,starts,...,crdy_stats_misc,crdr_stats_misc,2crdy,fls,fld,off,crs,int,tklw,og
2004,2005,Luis Orejuela,NaN,DF,Mallorca,es La Liga,NaN,NaN,1,1,...,0,0,0,1,4,0,2,1,0,0
2630,2631,Yael Trepy,NaN,FW,Cagliari,it Serie A,NaN,NaN,8,0,...,0,0,0,1,2,2,7,0,1,0

In [76]:
df_clean = df.dropna(subset=['age'])

In [77]:
df_clean.shape

(2837, 102)

In [78]:
df_clean['age'].isnull().sum()

np.int64(0)